#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 15 20:01:47 CEST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Manager0s1sROM_tb_behav -key {Behavioral:sim_1:Functional:Manager0s1sROM_tb} -tclbatch Manager0s1sROM_tb.tcl -log simulate.log"
xsim Manager0s1sROM_tb_behav -key {Behavioral:sim_1:Functional:Manager0s1sROM_tb} -tclbatch Manager0s1sROM_tb.tcl -log simulate.log

