#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 25 17:03:14 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 52a881550d2b435a9ddc3781f449babf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ComportamentalAddSub_tb_behav xil_defaultlib.ComportamentalAddSub_tb -log elaborate.log"
xelab -wto 52a881550d2b435a9ddc3781f449babf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ComportamentalAddSub_tb_behav xil_defaultlib.ComportamentalAddSub_tb -log elaborate.log

